### Server Configuration
server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


### Spring Configuration
spring:
  config:
    use-legacy-processing: true
  ### profiles
  profiles:
    include: oauth,aws

  ### Datasource
  datasource:
    driver-class-name: driver-class-name
    url: jdbc-url
    username: client id
    password: client password

  ### JPA
  jpa:
    show-sql: false
    properties:
      hibernate:
#        dialect: dialect
        format_sql: true
    hibernate:
      ddl_auto: update


