# S3 server
cloud:
  aws:
    credentials:
      accessKey: accesskey
      secretKey: secretkey
    s3:
      bucket: modongmun
    region:
      static: ap-northeast-2
    stack:
      auto: false

# EC2 warning
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
