spring:
  security:
    oauth2:
      client:
        ### Registration
        registration:
          # Google
          google:
            client-id: `client id`
            client-secret: `client password`
            scope:
              - profile
              - email

          # Naver
          naver:
            client-id: `client id`
            client-secret: `client password`
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          # Kakao
          kakao:
            client-id: `client id`
            client-secret: `client password`
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST  # https://devtalk.kakao.com/t/topic/113641/3 을 참조함. (검색 : Google - attempting to retrieve the OAuth 2.0 Access Token Response: 401)
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        ### Provider
        provider:
          # Naver
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          # Kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
